apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: zookeeper
    name: ubuntu
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ubuntu:16.04
      from:
        kind: DockerImage
        name: ubuntu:16.04
      generation: null
      importPolicy: {}
      name: "16.04"
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: zookeeper
    name: zookeeper
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: zookeeper:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: /zookeeper
      git:
        uri: https://github.com/iceman91176/k8s-statfulsets
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubuntu:16.04
      type: Docker
    triggers:
    - github:
        secret: B4mtvYSllzLtrDi4r-vO
      type: GitHub
    - generic:
        secret: wJV0V32JxsD4P790HoVE
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}

